### ISSUE TITLE
Too many masters

### ISSUE THREAD

**Issue by Velezarius** [MinLL/BaboKeywordPatcher#2]
Done.
Running patch.
Writing to output: C:\Users\x\AppData\Local\Temp\Synthesis\zpwkwgvv.drm\Workspace\Synthesis\1 - BaboKeywordPatcher\Synthesis.esp
System.ArgumentException: Synthesis.esp has too many masters on masters list
   at Mutagen.Bethesda.Plugins.Masters.MasterReferenceReader.SetTo(IEnumerable`1 masters)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.ConstructWriteMasters(IModGetter mod)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.PostProcessAdjustments(MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, Stream stream, BinaryWriteParameters param, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.WriteToBinaryParallel(ISkyrimModGetter item, String path, BinaryWriteParameters param, IFileSystem fileSystem)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.Mutagen.Bethesda.Plugins.Records.IModGetter.WriteToBinaryParallel(FilePath path, BinaryWriteParameters param, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 461
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 57
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 58
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 84

**Comment by MataGaming** [comment]
do you have other patchers in the group? if so, move it to a new group.

**Comment by Velezarius** [comment]
Creating groups didn't help... Another error:
"...Added keyword Skyrim.Keyword EroticArmor 08C7F6:SexLabAroused.esm to armor Vagrant Robes
Done.
Running patch.
Writing to output: C:\Users\BB2\AppData\Local\Temp\Synthesis\zpwkwgvv.drm\Workspace\Babo group\1 - BaboKeywordPatcher\Babo group.esp
System.ArgumentException: Synthesis.esp has too many masters on masters list
   at Mutagen.Bethesda.Plugins.Masters.MasterReferenceReader.SetTo(IEnumerable`1 masters)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.ConstructWriteMasters(IModGetter mod)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.PostProcessAdjustments(MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, Stream stream, BinaryWriteParameters param, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.WriteToBinaryParallel(ISkyrimModGetter item, String path, BinaryWriteParameters param, IFileSystem fileSystem)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.Mutagen.Bethesda.Plugins.Records.IModGetter.WriteToBinaryParallel(FilePath path, BinaryWriteParameters param, IFileSystem fileSystem)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 461
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 404
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 378
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 55
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 57
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 68"

**Comment by MataGaming** [comment]
in that case either blacklist some mods or combine some armor mods to lower the amount of masters, there's no way around the limit. it's a game engine thing.

**Comment by Velezarius** [comment]
Thanks for the clarification. I will experiment with disabling-enabling plugins with clothes...

**Comment by MinLL** [comment]
Yeah, nothing I can do about this one. This is an engine limitation as @MataGaming mentioned. You'll need to have it patch less plugins.

**Comment by MysticDaedra** [comment]
I realize this old, but thought I'd post anyways. For anyone else having this issue, just divide the armor mods up and create two patches. You'll want two separate groups with this synthesis patch.

1. Disable most armor mods, keep the enabled amount under the limit (I don't remember the limit, but I think it's 255?)
2. Create first patch
3. Disable first mods, enable next batch of armor mods
4. Create _second_ patch (separate from the first one, do not re-run the first group, it will overwrite!)

Repeat until all your armor and clothing mods are patched!
